config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'todos#index'
  resources :todos
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord

  validates :name, presence: true
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :todos, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :authenticate_user!

  def index
    @todos = current_user.todos.all
    respond_to do |format|
      format.html
      format.json { render json: @todos }
    end 

  end

  def new
    @todo = current_user.todos.build
  end

  def create
    @todo = current_user.todos.build(todo_params)
    if @todo.save
      redirect_to todos_url, notice: "タスク「#{@todo.name}」を登録しました。"
    else
      render :new
    end
  end

  def show
    @todo = current_user.todos.find(params[:id])
  end

  def edit
    @todo = current_user.todos.find(params[:id])
  end

  def update
    @todo = current_user.todos.find(params[:id])
    if @todo.update(todo_params)
      redirect_to todos_url, notice: "タスク「#{@todo.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    todo = current_user.todos.find(params[:id])
    todo.destroy
    redirect_to todos_url, notice: "タスク「#{todo.name}」を削除しました。"
  end

  private
    def todo_params
      params.require(:todo).permit(:name, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Task
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .app-title.navbar.navbar-expand-md.navbar-light.bg-light 
      .navbar-brand Taskleaf

      %ul.navbar-nav.ml-auto
        - if current_user
          %li.nav-item= link_to 'タスク一覧', todos_path, class: 'nav-link'
          %li.nav-item= link_to 'ログアウト', destroy_user_session_path, data: {method: 'delete'}, class: 'nav-link'
        - else
          %li.nav-item= link_to 'ログイン', user_session_path, class: 'nav-link'
    .container
      - if flash.notice.present?
        .alert.alert-succes= flash.notice
      = yield

app/views/todos/edit.html.haml
%h1 タスクの編集

.nav.justify-content-end
  = link_to '一覧', todos_path, class: 'nav-link'

= form_with(model: @todo, local: true) do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: "btn btn-primary"

app/views/todos/index.html.haml
%h1 タスク一覧

.btn.btn-primary.new
  = '新規登録'
.form-group.d-none
  = 'Name'
  = text_field_tag :todo_name, '', class: 'form-control'
  = 'Description'
  = text_area_tag :todo_description, '', class: 'form-control'
  .btn.btn-primary.add-todo-btn
    = '登録'

.mb-3
%table.table.table-hover
  %thead.thead-default
    %tr
      %th= Todo.human_attribute_name(:name)
      %th= Todo.human_attribute_name(:created_at)
      %th
  %tbody
    - @todos.each do |todo|
      %tr
        %td= link_to todo.name, todo_path(todo), class: 'text-decoration-none'
        %td= todo.created_at
        %td 
          = link_to '編集', edit_todo_path(todo), class: 'btn btn-primary mr-3'
          = link_to '削除', todo, method: :delete, data: {confirm: "タスク#{todo.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'

app/views/todos/new.html.haml
%h1 タスクの新規登録

.nav.justify-content-end
  = link_to '一覧', todos_path, class: 'nav-link'

= form_with(model: @todo, local: true) do |f|
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control', id: 'task_name'
  .form-group
    = f.label :description
    = f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'
  = f.submit nil, class: "btn btn-primary"

app/views/todos/show.html.haml
%h1 タスクの詳細

.nav.justify-content-end
  = link_to '一覧', todos_path, class: 'nav-link'
%table.table.table-hover
  %tbody
    %tr 
      %th= Todo.human_attribute_name(:id)
      %td= @todo.id
    %tr 
      %th= Todo.human_attribute_name(:name)
      %td= @todo.name
    %tr 
      %th= Todo.human_attribute_name(:description)
      %td= simple_format(h(@todo.description), {}, sanitize: false, wrapper_tag: "div")
    %tr 
      %th= Todo.human_attribute_name(:created_at)
      %td= @todo.created_at
    %tr 
      %th= Todo.human_attribute_name(:updated_at)
      %td= @todo.updated_at
= link_to '編集', edit_todo_path, class: 'btn btn-primary mr-3'
= link_to '削除', @todo, method: :delete, data: {confirm: "タスク#{@todo.name}を削除します。よろしいですか？"}, class: 'btn btn-danger'